// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViTTj4aOQySehd0WMOxkrRf5JjHKITeE',
    appId: '1:578909584286:web:00b65a4547ecdf81b6b48f',
    messagingSenderId: '578909584286',
    projectId: 'jobby-9308e',
    authDomain: 'jobby-9308e.firebaseapp.com',
    storageBucket: 'jobby-9308e.appspot.com',
    measurementId: 'G-JQQSR0YW1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMd1UAkxwzGt-vWnto53wt5M55NqttMXE',
    appId: '1:578909584286:android:44f3fc006a266a15b6b48f',
    messagingSenderId: '578909584286',
    projectId: 'jobby-9308e',
    storageBucket: 'jobby-9308e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDDvaOFmXlXy8ImrvmD_FDxtsXJFHitM',
    appId: '1:578909584286:ios:028c6280060997f9b6b48f',
    messagingSenderId: '578909584286',
    projectId: 'jobby-9308e',
    storageBucket: 'jobby-9308e.appspot.com',
    iosBundleId: 'com.example.jobby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvDDvaOFmXlXy8ImrvmD_FDxtsXJFHitM',
    appId: '1:578909584286:ios:028c6280060997f9b6b48f',
    messagingSenderId: '578909584286',
    projectId: 'jobby-9308e',
    storageBucket: 'jobby-9308e.appspot.com',
    iosBundleId: 'com.example.jobby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAViTTj4aOQySehd0WMOxkrRf5JjHKITeE',
    appId: '1:578909584286:web:cae566f91ce0073bb6b48f',
    messagingSenderId: '578909584286',
    projectId: 'jobby-9308e',
    authDomain: 'jobby-9308e.firebaseapp.com',
    storageBucket: 'jobby-9308e.appspot.com',
    measurementId: 'G-H0C69HT4EL',
  );
}
